export interface Question {
    id: number;
    text: string;
    options: string[];
    correctAnswer: number; // 1-based index
}

export interface ExamConfig {
    title: string;
    subject: string;
    totalQuestions: number;
    totalMarks: number;
    correctMarks: number;
    wrongMarks: number;
    durationMinutes: number;
    date: string;
}

export const examConfig: ExamConfig = {
    title: "CUET PG 2026 - Mock Test 4",
    subject: "Data Science, AI, Cyber Security & Computer Science",
    totalQuestions: 75,
    totalMarks: 300,
    correctMarks: 4,
    wrongMarks: -1,
    durationMinutes: 90,
    date: "Practice Test",
};

export const questions: Question[] = [
    {
        id: 1,
        text: "The number of onto (surjective) functions from a set with 4 elements to a set with 2 elements is:",
        options: [
            "8",
            "14",
            "16",
            "6",
        ],
        correctAnswer: 2,
    },
    {
        id: 2,
        text: "In Boolean Algebra, which law states that $A + A'B = A + B$?",
        options: [
            "Absorption law",
            "Consensus law",
            "Distributive law",
            "Idempotent law",
        ],
        correctAnswer: 1,
    },
    {
        id: 3,
        text: "A relation $R$ is transitive if:",
        options: [
            "$(a, b) \\in R$ implies $(b, a) \\in R$",
            "$(a, b) \\in R$ and $(b, c) \\in R$ implies $(a, c) \\in R$",
            "$(a, a) \\in R$ for all $a$",
            "$(a, b) \\in R$ and $(b, a) \\in R$ implies $a = b$",
        ],
        correctAnswer: 2,
    },
    {
        id: 4,
        text: "Which of the following properties does a lattice satisfy?\n\nA. Commutativity\nB. Associativity\nC. Absorption\nD. Identity\n\nChoose the correct answer from the options given below:",
        options: [
            "A, B and C only",
            "A, B and D only",
            "B, C and D only",
            "A, B, C and D",
        ],
        correctAnswer: 4,
    },
    {
        id: 5,
        text: "The regular expression $(a + b)^*a(a + b)^*$ denotes:",
        options: [
            "Strings containing at least one $'a'$",
            "Strings starting with $'a'$",
            "Strings ending with $'a'$",
            "Strings with exactly one $'a'$",
        ],
        correctAnswer: 1,
    },
    {
        id: 6,
        text: "An $\\epsilon$-NFA (Non-deterministic Finite Automaton with epsilon transitions) can be converted to:",
        options: [
            "DFA only",
            "NFA without $\\epsilon$-transitions only",
            "Both DFA and NFA without $\\epsilon$-transitions",
            "Neither DFA nor NFA",
        ],
        correctAnswer: 3,
    },
    {
        id: 7,
        text: "A language is context-free if and only if it can be generated by:",
        options: [
            "Regular grammar",
            "Context-free grammar",
            "Context-sensitive grammar",
            "Unrestricted grammar",
        ],
        correctAnswer: 2,
    },
    {
        id: 8,
        text: "The closure properties of context-free languages include:\n\nA. Union\nB. Concatenation\nC. Kleene star\nD. Intersection\n\nChoose the correct answer from the options given below:",
        options: [
            "A, B and C only",
            "A, B and D only",
            "B, C and D only",
            "A, B, C and D",
        ],
        correctAnswer: 1,
    },
    {
        id: 9,
        text: "The halting problem for Turing machines is:",
        options: [
            "Decidable",
            "Undecidable",
            "Semi-decidable",
            "Context-free",
        ],
        correctAnswer: 2,
    },
    {
        id: 10,
        text: "The Gray code for decimal 5 (assuming 4 bits) is:",
        options: [
            "0101",
            "0111",
            "0110",
            "1101",
        ],
        correctAnswer: 2,
    },
    {
        id: 11,
        text: "In excess-3 code, the decimal digit 6 is represented as:",
        options: [
            "0110",
            "1001",
            "1000",
            "0011",
        ],
        correctAnswer: 2,
    },
    {
        id: 12,
        text: "A 2-to-4 line decoder with enable input can function as:",
        options: [
            "Demultiplexer",
            "Multiplexer",
            "Encoder",
            "Comparator",
        ],
        correctAnswer: 1,
    },
    {
        id: 13,
        text: "The Boolean expression $(A + B)(A + C)$ can be simplified to:",
        options: [
            "$A + BC$",
            "$AC + BC$",
            "$A + B + C$",
            "$ABC$",
        ],
        correctAnswer: 1,
    },
    {
        id: 14,
        text: "A master-slave flip-flop is used to:",
        options: [
            "Increase speed",
            "Eliminate race condition",
            "Reduce power consumption",
            "Increase storage capacity",
        ],
        correctAnswer: 2,
    },
    {
        id: 15,
        text: "The resolution of an $n$-bit DAC (Digital-to-Analog Converter) is:",
        options: [
            "$1/n$",
            "$1/2^n$",
            "$2^n$",
            "$n$",
        ],
        correctAnswer: 2,
    },
    {
        id: 16,
        text: "In relative addressing mode, the effective address is calculated by adding:",
        options: [
            "Base register and offset",
            "Program counter and displacement",
            "Index register and base address",
            "Two registers",
        ],
        correctAnswer: 2,
    },
    {
        id: 17,
        text: "The main advantage of associative memory (CAM) is:",
        options: [
            "Low cost",
            "Large storage capacity",
            "Fast search based on content",
            "Non-volatility",
        ],
        correctAnswer: 3,
    },
    {
        id: 18,
        text: "In a write-back cache policy:",
        options: [
            "Data is written to both cache and memory simultaneously",
            "Data is written to cache only and to memory later",
            "Data is written to memory only",
            "Data is never written to cache",
        ],
        correctAnswer: 2,
    },
    {
        id: 19,
        text: "Which type of hazard occurs when an instruction depends on the result of a previous instruction?",
        options: [
            "Structural hazard",
            "Data hazard",
            "Control hazard",
            "Resource hazard",
        ],
        correctAnswer: 2,
    },
    {
        id: 20,
        text: "The Harvard architecture differs from Von Neumann architecture in having:",
        options: [
            "Separate memory for instructions and data",
            "Multiple processors",
            "Larger cache",
            "Faster clock speed",
        ],
        correctAnswer: 1,
    },
    {
        id: 21,
        text: "In 8085, the instruction XCHG exchanges the contents of:",
        options: [
            "Accumulator and B register",
            "HL and DE register pairs",
            "BC and DE register pairs",
            "Accumulator and memory",
        ],
        correctAnswer: 2,
    },
    {
        id: 22,
        text: "The DAD instruction in 8085 is used for:",
        options: [
            "8-bit addition",
            "16-bit addition to HL pair",
            "Decimal addition",
            "BCD addition",
        ],
        correctAnswer: 2,
    },
    {
        id: 23,
        text: "RST 7.5 interrupt in 8085 has a vector address of:",
        options: [
            "0024H",
            "002CH",
            "003CH",
            "0034H",
        ],
        correctAnswer: 3,
    },
    {
        id: 24,
        text: "The 8255 PPI (Programmable Peripheral Interface) has how many modes of operation?",
        options: [
            "2",
            "3",
            "4",
            "5",
        ],
        correctAnswer: 2,
    },
    {
        id: 25,
        text: "In 8085, the status signals S0 and S1 indicate:",
        options: [
            "Type of operation being performed",
            "Interrupt status",
            "Flag status",
            "Power status",
        ],
        correctAnswer: 1,
    },
    {
        id: 26,
        text: "The storage class 'static' in C means:",
        options: [
            "Variable exists throughout program execution",
            "Variable is stored on heap",
            "Variable cannot be modified",
            "Variable is automatically initialized to random value",
        ],
        correctAnswer: 1,
    },
    {
        id: 27,
        text: "In C, what is the return type of malloc() function?",
        options: [
            "int*",
            "void*",
            "char*",
            "float*",
        ],
        correctAnswer: 2,
    },
    {
        id: 28,
        text: "The time complexity of adding an element to a stack is:",
        options: [
            "$O(1)$",
            "$O(\\log n)$",
            "$O(n)$",
            "$O(n \\log n)$",
        ],
        correctAnswer: 1,
    },
    {
        id: 29,
        text: "In a priority queue implemented as a heap, the highest priority element is:",
        options: [
            "At a leaf node",
            "At the root",
            "At the middle level",
            "At any position",
        ],
        correctAnswer: 2,
    },
    {
        id: 30,
        text: "A deque (double-ended queue) allows insertion and deletion at:",
        options: [
            "Front only",
            "Rear only",
            "Both front and rear",
            "Middle only",
        ],
        correctAnswer: 3,
    },
    {
        id: 31,
        text: "The postorder traversal of a binary tree visits nodes in the order:",
        options: [
            "Root, Left, Right",
            "Left, Root, Right",
            "Left, Right, Root",
            "Right, Left, Root",
        ],
        correctAnswer: 3,
    },
    {
        id: 32,
        text: "A threaded binary tree is used to:",
        options: [
            "Save memory",
            "Enable faster traversal",
            "Allow multiple threads",
            "Store more data",
        ],
        correctAnswer: 2,
    },
    {
        id: 33,
        text: "In a B-tree of order $m$, each internal node can have at most:",
        options: [
            "$m$ children",
            "$m - 1$ children",
            "$2m$ children",
            "$m/2$ children",
        ],
        correctAnswer: 1,
    },
    {
        id: 34,
        text: "The time complexity of deleting an element from a heap is:",
        options: [
            "$O(1)$",
            "$O(\\log n)$",
            "$O(n)$",
            "$O(n \\log n)$",
        ],
        correctAnswer: 2,
    },
    {
        id: 35,
        text: "Which sorting algorithm is adaptive (performs better when input is partially sorted)?",
        options: [
            "Selection Sort",
            "Heap Sort",
            "Insertion Sort",
            "Merge Sort",
        ],
        correctAnswer: 3,
    },
    {
        id: 36,
        text: "The worst-case time complexity of Quick Sort can be improved to $O(n \\log n)$ by:",
        options: [
            "Using random pivot selection",
            "Using the first element as pivot",
            "Using the last element as pivot",
            "Not possible to improve",
        ],
        correctAnswer: 1,
    },
    {
        id: 37,
        text: "Radix sort has a time complexity of:",
        options: [
            "$O(n \\log n)$",
            "$O(n^2)$",
            "$O(d(n + k))$ where $d$ is number of digits",
            "$O(n)$",
        ],
        correctAnswer: 3,
    },
    {
        id: 38,
        text: "Binary search requires the input array to be:",
        options: [
            "Unsorted",
            "Sorted",
            "Partially sorted",
            "Reverse sorted",
        ],
        correctAnswer: 2,
    },
    {
        id: 39,
        text: "The 0/1 Knapsack problem is best solved using:",
        options: [
            "Greedy algorithm",
            "Dynamic programming",
            "Divide and conquer",
            "Linear search",
        ],
        correctAnswer: 2,
    },
    {
        id: 40,
        text: "The Matrix Chain Multiplication problem exhibits:",
        options: [
            "Greedy choice property",
            "Optimal substructure",
            "No optimal solution",
            "Linear complexity",
        ],
        correctAnswer: 2,
    },
    {
        id: 41,
        text: "Kruskal's algorithm uses which data structure for cycle detection?",
        options: [
            "Stack",
            "Queue",
            "Union-Find",
            "Hash table",
        ],
        correctAnswer: 3,
    },
    {
        id: 42,
        text: "The time complexity of Prim's algorithm using adjacency matrix is:",
        options: [
            "$O(V^2)$",
            "$O(V \\log V)$",
            "$O(E \\log V)$",
            "$O(V + E)$",
        ],
        correctAnswer: 1,
    },
    {
        id: 43,
        text: "Strongly connected components in a directed graph can be found using:",
        options: [
            "BFS only",
            "DFS only",
            "Kosaraju's algorithm using DFS",
            "Dijkstra's algorithm",
        ],
        correctAnswer: 3,
    },
    {
        id: 44,
        text: "Inter-process communication mechanisms include:\n\nA. Shared memory\nB. Message passing\nC. Pipes\nD. Sockets\n\nChoose the correct answer from the options given below:",
        options: [
            "A, B and C only",
            "A, B and D only",
            "B, C and D only",
            "A, B, C and D",
        ],
        correctAnswer: 4,
    },
    {
        id: 45,
        text: "A thread is sometimes called:",
        options: [
            "Heavyweight process",
            "Lightweight process",
            "Child process",
            "Parent process",
        ],
        correctAnswer: 2,
    },
    {
        id: 46,
        text: "In multilevel queue scheduling, processes are:",
        options: [
            "All in one queue",
            "Permanently assigned to queues based on properties",
            "Randomly distributed",
            "Always in ready state",
        ],
        correctAnswer: 2,
    },
    {
        id: 47,
        text: "The aging technique in scheduling is used to:",
        options: [
            "Increase priority of waiting processes",
            "Decrease priority of running processes",
            "Terminate old processes",
            "Create new processes",
        ],
        correctAnswer: 1,
    },
    {
        id: 48,
        text: "A monitor is a high-level synchronization construct that:",
        options: [
            "Allows only one process to execute its procedures at a time",
            "Allows multiple processes simultaneously",
            "Has no mutual exclusion",
            "Cannot use condition variables",
        ],
        correctAnswer: 1,
    },
    {
        id: 49,
        text: "The readers-writers problem can lead to:",
        options: [
            "Deadlock only",
            "Starvation only",
            "Both deadlock and starvation",
            "Neither deadlock nor starvation",
        ],
        correctAnswer: 2,
    },
    {
        id: 50,
        text: "Safe state in the context of deadlock avoidance means:",
        options: [
            "No deadlock exists",
            "System can allocate resources to processes in some order avoiding deadlock",
            "All processes have completed",
            "No processes are waiting",
        ],
        correctAnswer: 2,
    },
    {
        id: 51,
        text: "The FIFO page replacement algorithm suffers from:",
        options: [
            "Low hit ratio only",
            "Belady's anomaly",
            "High complexity",
            "No disadvantages",
        ],
        correctAnswer: 2,
    },
    {
        id: 52,
        text: "Translation Lookaside Buffer (TLB) is a cache for:",
        options: [
            "Program instructions",
            "Data",
            "Page table entries",
            "File system metadata",
        ],
        correctAnswer: 3,
    },
    {
        id: 53,
        text: "Segmentation suffers from:",
        options: [
            "Internal fragmentation",
            "External fragmentation",
            "No fragmentation",
            "Both internal and external fragmentation",
        ],
        correctAnswer: 2,
    },
    {
        id: 54,
        text: "The window size in TCP is used for:",
        options: [
            "Error detection",
            "Flow control",
            "Routing",
            "Addressing",
        ],
        correctAnswer: 2,
    },
    {
        id: 55,
        text: "In the OSI model, encryption and decryption are functions of:",
        options: [
            "Physical layer",
            "Data link layer",
            "Presentation layer",
            "Application layer",
        ],
        correctAnswer: 3,
    },
    {
        id: 56,
        text: "The minimum frame size in Ethernet is:",
        options: [
            "46 bytes",
            "64 bytes",
            "128 bytes",
            "1500 bytes",
        ],
        correctAnswer: 2,
    },
    {
        id: 57,
        text: "NAT (Network Address Translation) operates at:",
        options: [
            "Physical layer",
            "Data link layer",
            "Network layer",
            "Transport layer",
        ],
        correctAnswer: 3,
    },
    {
        id: 58,
        text: "The Go-Back-N protocol retransmits:",
        options: [
            "Only the frame in error",
            "All frames from the error frame onwards",
            "All frames",
            "No frames",
        ],
        correctAnswer: 2,
    },
    {
        id: 59,
        text: "HTTPS uses which port by default?",
        options: [
            "80",
            "8080",
            "443",
            "21",
        ],
        correctAnswer: 3,
    },
    {
        id: 60,
        text: "The purpose of DHCP (Dynamic Host Configuration Protocol) is to:",
        options: [
            "Translate domain names to IP addresses",
            "Automatically assign IP addresses to hosts",
            "Route packets",
            "Encrypt data",
        ],
        correctAnswer: 2,
    },
    {
        id: 61,
        text: "Link state routing protocols include:",
        options: [
            "RIP",
            "OSPF",
            "BGP",
            "IGRP",
        ],
        correctAnswer: 2,
    },
    {
        id: 62,
        text: "Uniform Cost Search expands nodes in order of:",
        options: [
            "Depth",
            "Heuristic value",
            "Path cost from start node",
            "Random order",
        ],
        correctAnswer: 3,
    },
    {
        id: 63,
        text: "Hill climbing is a:",
        options: [
            "Complete search algorithm",
            "Optimal search algorithm",
            "Local search algorithm",
            "Systematic search algorithm",
        ],
        correctAnswer: 3,
    },
    {
        id: 64,
        text: "Simulated annealing is inspired by:",
        options: [
            "Biological evolution",
            "Metallurgical process of heating and cooling",
            "Neural networks",
            "Genetic algorithms",
        ],
        correctAnswer: 2,
    },
    {
        id: 65,
        text: "In propositional logic, the biconditional $P \\leftrightarrow Q$ is true when:",
        options: [
            "$P$ and $Q$ have different truth values",
            "$P$ and $Q$ have the same truth values",
            "$P$ is true",
            "$Q$ is false",
        ],
        correctAnswer: 2,
    },
    {
        id: 66,
        text: "Skolemization in first-order logic is used to:",
        options: [
            "Add universal quantifiers",
            "Remove existential quantifiers",
            "Add predicates",
            "Remove predicates",
        ],
        correctAnswer: 2,
    },
    {
        id: 67,
        text: "Semantic networks represent knowledge using:",
        options: [
            "Rules only",
            "Nodes and labeled arcs",
            "Truth tables",
            "Decision trees",
        ],
        correctAnswer: 2,
    },
    {
        id: 68,
        text: "Backward chaining is used in:",
        options: [
            "Data-driven reasoning",
            "Goal-driven reasoning",
            "Forward reasoning",
            "Random reasoning",
        ],
        correctAnswer: 2,
    },
    {
        id: 69,
        text: "The Diffie-Hellman algorithm is used for:",
        options: [
            "Encryption",
            "Digital signatures",
            "Key exchange",
            "Hashing",
        ],
        correctAnswer: 3,
    },
    {
        id: 70,
        text: "A salt in password hashing is used to:",
        options: [
            "Increase password length",
            "Prevent rainbow table attacks",
            "Encrypt the password",
            "Compress the password",
        ],
        correctAnswer: 2,
    },
    {
        id: 71,
        text: "SSL/TLS operates at which layer?",
        options: [
            "Network layer",
            "Transport layer",
            "Between transport and application layer",
            "Physical layer",
        ],
        correctAnswer: 3,
    },
    {
        id: 72,
        text: "In unsupervised learning, the algorithm:",
        options: [
            "Learns from labeled data",
            "Finds patterns in unlabeled data",
            "Receives feedback from environment",
            "Requires ground truth",
        ],
        correctAnswer: 2,
    },
    {
        id: 73,
        text: "The elbow method is used to determine:",
        options: [
            "Number of features",
            "Optimal number of clusters in k-means",
            "Learning rate",
            "Training epochs",
        ],
        correctAnswer: 2,
    },
    {
        id: 74,
        text: "Precision in classification is defined as:",
        options: [
            "$TP / (TP + FP)$",
            "$TP / (TP + FN)$",
            "$(TP + TN) / Total$",
            "$TN / (TN + FP)$",
        ],
        correctAnswer: 1,
    },
    {
        id: 75,
        text: "Data normalization techniques include:\n\nA. Min-Max scaling\nB. Z-score normalization\nC. Decimal scaling\nD. Principal Component Analysis\n\nChoose the correct answer from the options given below:",
        options: [
            "A, B and C only",
            "A, B and D only",
            "B, C and D only",
            "A, B, C and D",
        ],
        correctAnswer: 1,
    },
];
